version: '3.8'

services:
  fraudshield-api:
    build: .
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
      - MONGODB_URI=mongodb://mongodb:27017/fraudshield
      - JWT_SECRET=your_production_jwt_secret_here
      - FIREBASE_API_KEY=AIzaSyD3-dP7FMPOA1PyHewcx6XfSJFNvkLSnOE
      - FIREBASE_AUTH_DOMAIN=fraud-detection-system-1c685.firebaseapp.com
      - FIREBASE_DATABASE_URL=https://fraud-detection-system-1c685-default-rtdb.firebaseio.com
      - FIREBASE_PROJECT_ID=fraud-detection-system-1c685
      - FIREBASE_STORAGE_BUCKET=fraud-detection-system-1c685.firebasestorage.app
      - FIREBASE_MESSAGING_SENDER_ID=23355196531
      - FIREBASE_APP_ID=1:23355196531:web:3856e15984c583a3fad606
      - FIREBASE_MEASUREMENT_ID=G-FLYW9H2GFV
    depends_on:
      - mongodb
    restart: unless-stopped

  mongodb:
    image: mongo:7-jammy
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    restart: unless-stopped

volumes:
  mongodb_data:
