name: fraudshield-api
services:
  - type: web
    name: backend
    runtime: node
    buildCommand: cd backend && npm install
    startCommand: cd backend && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        generateValue: true
      - key: JWT_SECRET
        generateValue: true
      - key: FIREBASE_API_KEY
        fromService:
          type: secret
          name: firebase-config
      - key: FIREBASE_AUTH_DOMAIN
        fromService:
          type: secret
          name: firebase-config
      - key: FIREBASE_DATABASE_URL
        fromService:
          type: secret
          name: firebase-config
      - key: FIREBASE_PROJECT_ID
        fromService:
          type: secret
          name: firebase-config
      - key: FIREBASE_STORAGE_BUCKET
        fromService:
          type: secret
          name: firebase-config
      - key: FIREBASE_MESSAGING_SENDER_ID
        fromService:
          type: secret
          name: firebase-config
      - key: FIREBASE_APP_ID
        fromService:
          type: secret
          name: firebase-config
      - key: FIREBASE_MEASUREMENT_ID
        fromService:
          type: secret
          name: firebase-config
