name = "fraudshield-api"

[[services]]
type = "web"
name = "backend"
runtime = "node"
buildCommand = "cd backend && npm install"
startCommand = "cd backend && npm start"

[[services.envVars]]
key = "NODE_ENV"
value = "production"

[[services.envVars]]
key = "MONGODB_URI"
generateValue = true

[[services.envVars]]
key = "JWT_SECRET"
generateValue = true

[[services.envVars]]
key = "FIREBASE_API_KEY"
value = "AIzaSyD3-dP7FMPOA1PyHewcx6XfSJFNvkLSnOE"

[[services.envVars]]
key = "FIREBASE_AUTH_DOMAIN"
value = "fraud-detection-system-1c685.firebaseapp.com"

[[services.envVars]]
key = "FIREBASE_DATABASE_URL"
value = "https://fraud-detection-system-1c685-default-rtdb.firebaseio.com"

[[services.envVars]]
key = "FIREBASE_PROJECT_ID"
value = "fraud-detection-system-1c685"

[[services.envVars]]
key = "FIREBASE_STORAGE_BUCKET"
value = "fraud-detection-system-1c685.firebasestorage.app"

[[services.envVars]]
key = "FIREBASE_MESSAGING_SENDER_ID"
value = "23355196531"

[[services.envVars]]
key = "FIREBASE_APP_ID"
value = "1:23355196531:web:3856e15984c583a3fad606"

[[services.envVars]]
key = "FIREBASE_MEASUREMENT_ID"
value = "G-FLYW9H2GFV"
